name: "プルリクのレビュアーの抽選"
on:
  pull_request:
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 現ブランチからチェックアウト
        uses: actions/checkout@v2

      - name: 抽選を開始
        uses: uesteibar/reviewer-lottery@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}